.dashBlueprintComponents_js_metadata <- function() {
deps_metadata <- list(`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-all-paths-loader.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-all-paths.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-split-paths-by-size-loader.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-all-paths-loader.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-all-paths.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-blueprint-icons-split-paths-by-size-loader.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_blueprint_components.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_blueprint_components.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components-shared` = structure(list(name = "dash_blueprint_components-shared",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_blueprint_components-shared.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components-shared` = structure(list(name = "dash_blueprint_components-shared",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_blueprint_components-shared.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'normalize.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-icons.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-icons.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-select.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-select.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-datetime.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-datetime.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-datetime2.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'blueprint-datetime2.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'docs-theme.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'docs-theme.css.map', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = NULL,
stylesheet = 'sidebar.css', head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-16.eot',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-16.svg',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-16.ttf',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-16.woff',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-16.woff2',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-20.eot',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-20.svg',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-20.ttf',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-20.woff',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"),
`dash_blueprint_components` = structure(list(name = "dash_blueprint_components",
version = "0.1.0", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'blueprint-icons-20.woff2',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashBlueprintComponents",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
